const wiktionaryLanguages = [
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Ancient Greek",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Asturian",
    "Avar",
    "Aymara",
    "Azerbaijani",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bishnupriya Manipuri",
    "Bosnian",
    "Breton",
    "Buginese",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Cebuano",
    "Central Atlas Tamazight",
    "Central Bicolano",
    "Chechen",
    "Cherokee",
    "Cheyenne",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Crimean Tatar",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dogri",
    "Dutch",
    "Egyptian Arabic",
    "Emilian-Romagnol",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Extremaduran",
    "Farsi",
    "Fijian",
    "Finnish",
    "Franco-Provençal/Arpitan",
    "French",
    "Friulian",
    "Frisian",
    "Gaelic",
    "Galician",
    "Gan Chinese",
    "Georgian",
    "German",
    "Gilbertese",
    "Gothic",
    "Greek",
    "Greenlandic",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hakka Chinese",
    "Hawaiian",
    "Hebrew",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Iloko",
    "Inari Sami",
    "Indonesian",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kabyle",
    "Kalaallisut",
    "Kannada",
    "Kapampangan",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Kirundi",
    "Komi",
    "Kongo",
    "Konkani",
    "Korean",
    "Koryak",
    "Krio",
    "Kurdish",
    "Ladino",
    "Lao",
    "Latin",
    "Latvian",
    "Ligurian",
    "Limburgish",
    "Lingala",
    "Lithuanian",
    "Livonian",
    "Lojban",
    "Lombard",
    "Low German",
    "Lower Sorbian",
    "Luganda",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Mandinka",
    "Maori",
    "Marathi",
    "Mari",
    "Marshallese",
    "Mazandarani",
    "Meänkieli",
    "Min Dong Chinese",
    "Min Nan Chinese",
    "Mingrelian",
    "Mirandese",
    "Moksha",
    "Mongolian",
    "Morisyen",
    "Mossi",
    "Mwani",
    "Nahuatl",
    "Nauruan",
    "Navajo",
    "Ndonga",
    "Nepali",
    "Newar",
    "Ngambay",
    "Nias",
    "Nogai",
    "North Frisian",
    "Northern Sami",
    "Northern Sotho",
    "Norwegian",
    "Novial",
    "Nāhuatl",
    "Occitan",
    "Ojibwe",
    "Old English",
    "Old High German",
    "Old Norse",
    "Old Occitan",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Pali",
    "Pampangan",
    "Pashto",
    "Pennsylvania German",
    "Pijin",
    "Punjabi",
    "Quechua",
    "Ripuarian",
    "Romani",
    "Romanian",
    "Romansh",
    "Russian",
    "Rusyn",
    "Sakha",
    "Samoan",
    "Samogitian",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Scots",
    "Scottish Gaelic",
    "Seediq",
    "Serbian",
    "Serbo-Croatian",
    "Sesotho",
    "Shan",
    "Shona",
    "Sicilian",
    "Silesian",
    "Simplified Chinese",
    "Sindhi",
    "Sinhalese",
    "Slovak",
    "Slovenian",
    "Somali",
    "Soninke",
    "South Azerbaijani",
    "Southern Altai",
    "Southern Sami",
    "Southern Sotho",
    "Spanish",
    "Sranan Tongo",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Temne",
    "Tetum",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tongan",
    "Tswana",
    "Tulu",
    "Turkish",
    "Turkmen",
    "Twi",
    "Udmurt",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uyghur",
    "Uzbek",
    "Venda",
    "Venetian",
    "Veps",
    "Vietnamese",
    "Volapük",
    "Võro",
    "Walloon",
    "Waray-Waray",
    "Welsh",
    "West Frisian",
    "Western Armenian",
    "Western Balochi",
    "Western Punjabi",
    "Wolof",
    "Wu Chinese",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Yue Chinese",
    "Zazaki",
    "Zeelandic",
    "Zhuang",
    "Zulu"
  ];

const dataList = document.getElementById("languages")

let list = ""

for (let i = 0; i < wiktionaryLanguages.length; ++i){
    list += `<option value="${wiktionaryLanguages[i]}"> \n`
}
console.log(list)

dataList.innerHTML = list